export const products = [
  {
    type: "Cestas básicas",
    baskets: [
      {
        name: "Econômica",
        items: [
          "4Kg Arroz Branco T-1",
          "2Kg Açúcar Refinado Especial",
          "1Kg Farinha de Trigo Especial",
          "1Kg de Feijão Preto T-1",
          "1Kg Sal Refinado",
          "1 Gf Óleo de Soja 900ml",
          "2 Pct Massa com Ovos 500g",
          "1 Pct de Bolacha Sortida 350/400g",
          "1 Pct de Café 250g",
          "1 Un Molho Tomate 340g",
        ],
      },
      {
        name: "Especial",
        items: [
          "10Kg Arroz Branco T-1",
          "10Kg Açúcar Refinado",
          "5Kg Farinha de Trigo Especial",
          "3Kg de Feijão Preto ou Lentilha 500g",
          "1Kg Sal Refinado ou Pote de Tempero",
          "4 Gf Óleo de Soja 900ml",
          "3 Pct Massa c/ Ovos 500g ou 2 Pct Caseira",
          "2 Pct de Bolacha Maria/Sortida ou Salgada 400g",
          "2 Pct de Café 500g ou 3 Cx Melitta 250g",
          "1 Pct Polentina 500g ou Farinha de Milho",
          "1 Pct Farinha de Mandioca 500g",
          "1 Pct Erva Mate 500g",
          "1 Pct Suco 35g",
          "1 Lt/Cx Extrato de Tomate 350g",
          "1 Lt de Milho Verde 200g",
          "1 Lt de Ervilha 200g",
          "1 Cx Gelatina ou Pudim 85g/35g",
          "1 Gf Vinagre 750ml",
          "1 Pote Doce de Frutas 400g",
        ],
      },
      {
        name: "T-1",
        items: [
          "5Kg Arroz Branco T-1",
          "3Kg Açúcar Refinado",
          "2Kg Farinha de Trigo Especial",
          "2Kg de Feijão Preto ou Lentilha 500g",
          "1Kg Sal Refinado ou Pote de Tempero",
          "2 Gf Óleo de Soja 900ml",
          "2 Pct Massa c/ Ovos 500g",
          "1 Pct de Bolacha Maria/Sortida 350/400g",
          "1 Pct Polentina 500g ou Farinha de Milho",
          "1 Pct de Café 250g",
          "1 Un Molho de Tomate 340g",
        ],
      },
      {
        name: "T-2",
        items: [
          "7Kg Arroz Branco T-1",
          "4Kg Açúcar Refinado",
          "2Kg Farinha de Trigo Especial",
          "2Kg de Feijão Preto ou Lentilha 500g",
          "1Kg Sal Refinado ou Pote de Tempero",
          "3 Gf Óleo de Soja 900ml",
          "2 Pct Massa c/ Ovos 500g",
          "1 Pct de Bolacha Maria/Sortida 350/400g",
          "1 Pct Polentina 500g ou Farinha de Milho",
          "1 Pct Café 500g ou 1 Pct Melitta 250g",
          "1 Pct Erva Mate 500g",
          "1 Un Molho de Tomate 340g",
          "1 Pote Doce de Frutas 400g",
        ],
      },
      {
        name: "T-3",
        items: [
          "10Kg Arroz Branco T-1",
          "5Kg Açúcar Refinado",
          "5Kg Farinha de Trigo Especial",
          "2Kg de Feijão Preto ou Lentilha 500g",
          "1Kg Sal Refinado ou Pote de Tempero",
          "4 Gf Óleo de Soja 900ml",
          "3 Pct Massa c/ Ovos 500g ou 2 Pct Caseira",
          "1 Pct de Bolacha Sortida 350/400g",
          "1 Pct Bolacha Maria ou Salgada 350/400g",
          "3 Pct Café 250g ou 1 Pct Melitta 500g",
          "1 Pct Polentina 500g ou Farinha de Milho",
          "1 Pct Farofa Pronta 500g ou Pct Bolo 400g",
          "1 Pct Suco 45g",
          "1 Pct Fermento de Bolo ou Pão 10g",
          "1 Un Molho de Tomate 340g",
          "1 Lt Ervilha ou Molho Verde 200g",
          "1 Cx Gelatina ou Pudim 85g/35g",
        ],
      },
    ],
  },
  {
    type: "Ranchos",
    baskets: [
      {
        name: "Básico mensal",
        items: [
          "15Kg Arroz Branco T-1",
          "10Kg Açúcar Refinado Especial",
          "5Kg Farinha de Trigo Especial T-1",
          "4Kg de Feijão Preto T-1 ou Lentilha 500g",
          "1Kg Sal Refinado ou Pote de Tempero",
          "2 Cx Café Melitta 500g",
          "6 Gf Óleo de Soja 900ml",
          "3 Pct Massa c/ Ovos 500g ou 2 Pct Caseira",
          "1 Pct de Bolacha Salgada 350/400g",
          "1 Pct de Bolacha Maria/Sortida 350/400g",
          "1 Pct de Farofa Pronta 500g",
          "1 Pct Polentina 500g ou Farinha de Milho",
          "2 Pct de Suco 45g Sortido",
          "1 Lt de Milho Verde 200g",
          "1 Lt de Ervilha 200g",
          "1 Lt de Sardinha 130g ou Salsicha 180g",
          "2 Lt de Extrato de Tomate 350g",
          "1 Lt de Achocolatado Nescau ou Toddy 400g",
          "1 Cx Gelatina ou Pudim 85g/35g",
          "1 Gf Vinagre 750ml",
          "1 Un Doce de Leite 400g",
        ],
      },
    ],
  },
  {
    type: "Higiene e limpeza",
    baskets: [
      {
        name: "Básico",
        items: [
          "1 Pct Papel Higiênico c/ 4 Rolos 30mts",
          "1 Pct de Lã de Aço 60g",
          "2 Un Sabão de Barra 400g",
          "1 un Sabão Azul Barra 200g",
          "1 un Sabão em Pó 500g",
          "3 Un Sabonete 90g",
          "1 Un Alvejante 1l",
          "1 un Detergente 500ml",
          "1 Un Creme Dental 70g",
        ],
      },
      {
        name: "Mensal",
        items: [
          "1 Pct Papel Higiênico c/ 4 Rolos 60mts",
          "1 Pct de Lã de Aço 60g",
          "1 Un de Esponja Dupla Face",
          "1 cj Sabão Azul c/ 5 unidades 200g",
          "1 Cx Sabão em Pó Omo 800g",
          "2 un Detergente 500ml",
          "1 Un Desinfetante 500ml",
          "1 Un Alvejante 1l",
          "4 Un Sabonete 90g",
          "2 Un Creme Dental 90g",
          "1 Un Amaciante 2l",
        ],
      },
    ],
  },
];
